version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data

  escr-app:
    depends_on:
      - db
    image: javierpazz/jpzecofacesc:1.0.10
    # image: javierpazz/jpzstutz
    # image: stutz
    ports:
      - 4000:3000
    environment:
      JWT_SECRET: ${JWT_SECRET}

    restart: always
